FROM python:3.11-slim

WORKDIR /app

COPY scheduling_service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy service code
COPY scheduling_service/ ./

CMD ["python", "app_server.py"]
